export const DOMAIN = 'http://192.168.0.103:8000';

export const GET_NEWFEED_REQUEST = 'GET_NEWFEED_REQUEST';
export const GET_NEWFEED_SUCCESS = 'GET_NEWFEED_SUCCESS';
export const GET_NEWFEED_FAILURE = 'GET_NEWFEED_FAILURE';

export const GET_USER_NEWFEED_REQUEST = 'GET_USER_NEWFEED_REQUEST';
export const GET_USER_NEWFEED_SUCCESS = 'GET_USER_NEWFEED_SUCCESS';
export const GET_USER_NEWFEED_FAILURE = 'GET_USER_NEWFEED_FAILURE';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILURE = 'GET_ALL_USER_FAILURE';


